### ISSUE TITLE
Fuglu is not taking userconfig in SAPlugin

### ISSUE THREAD

**Issue by broedli** [gryphius/fuglu#90]
Hey, 
I believe I've discovered a problem concerning the `peruserconfig=1` setting in the SAPlugin.
Here is the relevant info (I hope I didn't forget something): https://paste.ttlab.de/m-oMRc/

The highspamlevel is set to 3 (for testing purposes) and should reject the incomming mails. But it treats them as normal spam and sorts it into `.Junk`.

However if I manually adjust the `highspamlevel=` to the value 3 I get the wanted behaviour:
```
Mar  2 13:51:45 vps98295 postfix/smtpd[28429]: proxy-reject: END-OF-MESSAGE: 550 message identified as spam; from=<securitycheck@emailsecuritycheck.net> to=<test@test.pultschlampe.de> proto=ESMTP helo=<emailsecuritycheck.net>
```

Help would be appreciated.

Related Issue: andryyy/mailcow#750

**Comment by broedli** [comment]
Doh, I've destroyed the multipaste ...
Here are the single pastes:
* fuglu.conf: https://paste.ttlab.de/NXaf/
* mysql table: https://paste.ttlab.de/IoL/
* mail.log: https://paste.ttlab.de/oMEM/

**Comment by gryphius** [comment]
I think there's a confusion between two things here: The "peruserconfig" setting from the SAPlugin enables Spamassassin's "User prefs". This is enabled by default afaik and just tells spamassasin "Please try to load individual rules for the recipient instead of just using the global ones." . User prefs can be in files or in a databse, but this lookup is configured within spamassassin. Fuglu does not know about that.

Your mysql table however looks like you're trying to enable dynamic fuglu configurations ("highspamlevel" is a concept that fuglu knows, but Spamassassin doesn't ). For that to work you need to enable database lookups  (as described in  http://gryphius.github.io/fuglu/configuration-index.html#fetching-scan-time-configuration-values-from-a-database ) .

**Comment by broedli** [comment]
Hey, thanks for your response!

Yes my wording was poor in the initial posting :pensive:
The lookup is actually setup and as far as I can tell the used (custom) sql statement looks correct: https://github.com/andryyy/mailcow/blob/master/fuglu/conf/fuglu.conf#L90-L92

However I've checked `fuglu --lint` and get the following error:
```
# fuglu --lint                    
Fuglu 0.6.6
---------- LINT MODE ----------
Checking dependencies...
sqlalchemy: installed
BeautifulSoup: V3 installed
magic: found python-file/libmagic bindings (http://www.darwinsys.com/file/)
Loading extensions...
fuglu.extensions.sql: enabled (available)
Loading plugins...
Plugin loading complete
Linting  main configuration
OK

Linting  sql configuration
Failed No module named MySQLdb
[...]
```

**Comment by gryphius** [comment]
```Failed No module named MySQLdb```
 -> you're missing the python MySQLdb library . 

Install it using your OS's package manager (`yum install MySQL-python` / `apt-get install python-mysqldb` / ... ) or with `pip install MySQL-python`

**Comment by broedli** [comment]
thank you for your patience!
The problem is resolved!
