### ISSUE TITLE
Feature request: command line client for fuglu

### ISSUE THREAD

**Issue by jahlives** [gryphius/fuglu#98]
It would be very helpful to have a cli client for fuglu. It should accept a msg from stdin, mangle it through full fuglu and in the end instead of re-injecting into postfix just print msg content to stdout.
Could help debugging fuglu issues, rescan messages after changes to fuglu/av/sa config or as a filter for programs that fetch mails from external accounts and pipe them through a cli filter.

**Comment by gryphius** [comment]
I like the idea! We already have `fuglu_debug` which pipes a message through fuglu without reinjects, but for the getmail case this doesn't help. 

There are multiple ways how we could implement this. 
 1. We could extend the netcat connector to return the resulting message and write a little wrapper similar to fuglu_debug
 2.  We could call the fuglu scan session directly from a dedicated script (similar to "plugdummy.py"). This would execute all plugins without a running fuglu daemon.  A little slower than option 1 because everything would be reloaded for each message but easier in installation and handling

I currently tend towards 2 (after thinking about it for maybe 10 minutes), but I see merit in both

**Comment by gryphius** [comment]
appender plugins would be problematic in option 2. Should we just skip them, or block until they are completed or start a new process in the background ... ?

**Comment by jahlives** [comment]
Hm I think for debugging/testing purpose option 1. could be the better choice. So it tests a running fuglu instance that is used for real message processing as well.  I think for option two one has to install/setup sa and clam anyway, then there is just a little bit more effort to get fuglu daemon up and running :-)
I personally would tend to option 1. although I can live with option 2.  without problems

----- Originale Nachricht -----
Von: Oli <notifications@github.com>
Gesendet: 04.08.2017 - 18:18
An: gryphius/fuglu <fuglu@noreply.github.com>
Betreff: Re: [gryphius/fuglu] Feature request: command line client for fuglu (#98)

**Comment by gryphius** [comment]
merged in https://github.com/gryphius/fuglu/commit/af91afccda177726f0e8fdfa61ec7c5643896ced
